   pipeline {
    agent any

  stages {


    stage("Initial cleanup") {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage("Clean up") {
      steps {
        cleanWs()
      }
    }





    }
}
